package cacs;

import java.util.ArrayList;

public class cacsconfig extends cacs{

		static String testCaseIdentifier;
		static String methodologyYear;
		static String reportingFacilityAmbCareNumber;
		static String fiscalYear;
		static String fiscalPeriod;
		static String batchNumber;
		static String abstractNumber;
		static String ageCode;
		static String ageNumber;
		static String gender;
		static String weightInGrams;
		static String gestationalAgeAtAdmission;
		static String gestationalAgeAtDelivery;
		static String gestationalAgeAtDischarge;
		static String medicalCMG;
		static String entryCode;
		static String acuteInstitutionFromTransferIndicator;
		static String dischargeDisposition;
		static String acuteInstitutionToTransferIndicator;
		static String totalLOS;
		static String acuteLOS;
		static String codingClassificationSystem;
		static String dx1SequenceNumber;
		static String dx1Code;
		static String dx1Type;
		static String dx2SequenceNumber;
		static String dx2Code;
		static String dx2Type;
		static String dx3SequenceNumber;
		static String dx3Code;
		static String dx3Type;
		static String dx4SequenceNumber;
		static String dx4Code;
		static String dx4Type;
		static String dx5SequenceNumber;
		static String dx5Code;
		static String dx5Type;
		static String dx6SequenceNumber;
		static String dx6Code;
		static String dx6Type;
		static String dx7SequenceNumber;
		static String dx7Code;
		static String dx7Type;
		static String dx8SequenceNumber;
		static String dx8Code;
		static String dx8Type;
		static String dx9SequenceNumber;
		static String dx9Code;
		static String dx9Type;
		static String dx10SequenceNumber;
		static String dx10Code;
		static String dx10Type;
		static String dx11SequenceNumber;
		static String dx11Code;
		static String dx11Type;
		static String dx12SequenceNumber;
		static String dx12Code;
		static String dx12Type;
		static String dx13SequenceNumber;
		static String dx13Code;
		static String dx13Type;
		static String dx14SequenceNumber;
		static String dx14Code;
		static String dx14Type;
		static String dx15SequenceNumber;
		static String dx15Code;
		static String dx15Type;
		static String dx165SequenceNumber;
		static String dx16Code;
		static String dx16Type;
		static String dx17SequenceNumber;
		static String dx17Code;
		static String dx17Type;
		static String dx18SequenceNumber;
		static String dx18Code;
		static String dx18Type;
		static String dx19SequenceNumber;
		static String dx19Code;
		static String dx19Type;
		static String dx20SequenceNumber;
		static String dx20Code;
		static String dx20Type;
		static String dx21SequenceNumber;
		static String dx21Code;
		static String dx21Type;
		static String dx225SequenceNumber;
		static String dx22Code;
		static String dx22Type;
		static String dx23SequenceNumber;
		static String dx23Code;
		static String dx23Type;
		static String dx24SequenceNumber;
		static String dx24Code;
		static String dx24Type;
		static String dx25SequenceNumber;
		static String dx25Code;
		static String dx25Type;
		static String episodeSequenceNumber1;
		static String interventionWithinEpisodeSequenceNumber1;
		static String interventionCode1;
		static String statusAttributeCode1;
		static String locationAttributeCode1;
		static String extentAttribute1;
		static String anaestheticTechnique1;
		static String oohIndicator1;
		static String episodeSequenceNumber2;
		static String interventionWithinEpisodeSequenceNumber2;
		static String interventionCode2;
		static String statusAttributeCode2;
		static String locationAttributeCode2;
		static String extentAttribute2;
		static String anaestheticTechnique2;
		static String oohIndicator2;
		static String episodeSequenceNumber3;
		static String interventionWithinEpisodeSequenceNumber3;
		static String interventionCode3;
		static String statusAttributeCode3;
		static String locationAttributeCode3;
		static String extentAttribute3;
		static String anaestheticTechnique3;
		static String oohIndicator3;
		static String episodeSequenceNumber4;
		static String interventionWithinEpisodeSequenceNumber4;
		static String interventionCode4;
		static String statusAttributeCode4;
		static String locationAttributeCode4;
		static String extentAttribute4;
		static String anaestheticTechnique4;
		static String oohIndicator4;
		static String episodeSequenceNumber5;
		static String interventionWithinEpisodeSequenceNumber5;
		static String interventionCode5;
		static String statusAttributeCode5;
		static String locationAttributeCode5;
		static String extentAttribute5;
		static String anaestheticTechnique5;
		static String oohIndicator5;
		static String episodeSequenceNumber6;
		static String interventionWithinEpisodeSequenceNumber6;
		static String interventionCode6;
		static String statusAttributeCode6;
		static String locationAttributeCode6;
		static String extentAttribute6;
		static String anaestheticTechnique6;
		static String oohIndicator6;
		static String episodeSequenceNumber7;
		static String interventionWithinEpisodeSequenceNumber7;
		static String interventionCode7;
		static String statusAttributeCode7;
		static String locationAttributeCode7;
		static String extentAttribute7;
		static String anaestheticTechnique7;
		static String oohIndicator7;
		static String episodeSequenceNumber8;
		static String interventionWithinEpisodeSequenceNumber8;
		static String interventionCode8;
		static String statusAttributeCode8;
		static String locationAttributeCode8;
		static String extentAttribute8;
		static String anaestheticTechnique8;
		static String oohIndicator8;
		static String episodeSequenceNumber9;
		static String interventionWithinEpisodeSequenceNumber9;
		static String interventionCode9;
		static String statusAttributeCode9;
		static String locationAttributeCode9;
		static String extentAttribute9;
		static String anaestheticTechnique9;
		static String oohIndicator9;
		static String episodeSequenceNumber10;
		static String interventionWithinEpisodeSequenceNumber10;
		static String interventionCode10;
		static String statusAttributeCode10;
		static String locationAttributeCode10;
		static String extentAttribute10;
		static String anaestheticTechnique10;
		static String oohIndicator10;
		static String episodeSequenceNumber11;
		static String interventionWithinEpisodeSequenceNumber11;
		static String interventionCode11;
		static String statusAttributeCode11;
		static String locationAttributeCode11;
		static String extentAttribute11;
		static String anaestheticTechnique11;
		static String oohIndicator11;
		static String episodeSequenceNumber12;
		static String interventionWithinEpisodeSequenceNumber12;
		static String interventionCode12;
		static String statusAttributeCode12;
		static String locationAttributeCode12;
		static String extentAttribute12;
		static String anaestheticTechnique12;
		static String oohIndicator12;
		static String episodeSequenceNumber13;
		static String interventionWithinEpisodeSequenceNumber13;
		static String interventionCode13;
		static String statusAttributeCode13;
		static String locationAttributeCode13;
		static String extentAttribute13;
		static String anaestheticTechnique13;
		static String oohIndicator13;
		static String episodeSequenceNumber14;
		static String interventionWithinEpisodeSequenceNumber14;
		static String interventionCode14;
		static String statusAttributeCode14;
		static String locationAttributeCode14;
		static String extentAttribute14;
		static String anaestheticTechnique14;
		static String oohIndicator14;
		static String episodeSequenceNumber15;
		static String interventionWithinEpisodeSequenceNumber15;
		static String interventionCode15;
		static String statusAttributeCode15;
		static String locationAttributeCode15;
		static String extentAttribute15;
		static String anaestheticTechnique15;
		static String oohIndicator15;
		static String episodeSequenceNumber16;
		static String interventionWithinEpisodeSequenceNumber16;
		static String interventionCode16;
		static String statusAttributeCode16;
		static String locationAttributeCode16;
		static String extentAttribute16;
		static String anaestheticTechnique16;
		static String oohIndicator16;
		static String episodeSequenceNumber17;
		static String interventionWithinEpisodeSequenceNumber17;
		static String interventionCode17;
		static String statusAttributeCode17;
		static String locationAttributeCode17;
		static String extentAttribute17;
		static String anaestheticTechnique17;
		static String oohIndicator17;
		static String episodeSequenceNumber18;
		static String interventionWithinEpisodeSequenceNumber18;
		static String interventionCode18;
		static String statusAttributeCode18;
		static String locationAttributeCode18;
		static String extentAttribute18;
		static String anaestheticTechnique18;
		static String oohIndicator18;
		static String episodeSequenceNumber19;
		static String interventionWithinEpisodeSequenceNumber19;
		static String interventionCode19;
		static String statusAttributeCode19;
		static String locationAttributeCode19;
		static String extentAttribute19;
		static String anaestheticTechnique19;
		static String oohIndicator19;
		static String episodeSequenceNumber20;
		static String interventionWithinEpisodeSequenceNumber20;
		static String interventionCode20;
		static String statusAttributeCode20;
		static String locationAttributeCode20;
		static String extentAttribute20;
		static String anaestheticTechnique20;
		static String oohIndicator20;
		static String mcc;
		static String mccPartition;
		static String mccSubPartition;
		static String cmg;
		static String coMorbidityLevel;
		static String cmgAgeCategory;
		static String coMorbidityTotalCount;
		static String flaggedInterventionStatusCode;
		static String filler;
		static String interventionEventCountCode;
		static String interventionOOHCountCode;
		static String interventionEpisodeUsedForCMGAssignment;
		static String interventionUsedForCMGAssignment;
		static String statusAttributeUsedForCMGAssignment;
		static String locationAttributeUsedForCMGAssignment;
		static String extentAttributeUsedForCMGAssignment;
		static String firstInterventionUsedForCMGSplit;
		static String statusAttributeUsedForCMGSplit;
		static String locationAttributeUsedForCMGSplit;
		static String extentAttributeUsedForCMGSplit;
		static String cmgWeightCategoryCode;
		static String dxCodeUsedForCMGAssignment;
		static String dxTypeUsedForCMGAssignment;
		static String firstdxCodeUsedInCMGSplit;
		static String inpatientRIWValue;
		static String CACS;
		static String CACSRIW;
		static String interventionUsedForCACSAssignment;
		static String statusAttributeUsedForCACSAssignment;
		static String locationAttributeUsedForCACSAssignment;
		static String extentAttributeUsedForCACSAssignment;
		static String CACSAnaestheticCode;
		static String filler1;
		static String eLOSDays;
		static String trimDays;
		static String inpatientRIWAtypicalCode;
		static String inpatientRIperdiem;
		static String inpatientRItotalfactor;
		static String inpatientRIlevel;
		static String branchCode;
		static String coMorbidityTotalFactor;
		static String flaggedInterventionFlagCardioversion;
		static String flaggedInterventionFlagChemotherapy;
		static String flaggedInterventionFlagCellSaver;
		static String flaggedInterventionFlagDialysis;
		static String flaggedInterventionFlagFeedingTube;
		static String flaggedInterventionFlagHeartResuscitation;
		static String flaggedInterventionFlagInvasiveVentilationEqualOrGreaterThan96hrs;
		static String flaggedInterventionFlagInvasiveVentilationLessThan96hrs;
		static String flaggedInterventionFlagParacentesis;
		static String flaggedInterventionFlagParenteralNutrition;
		static String flaggedInterventionFlagPleurocentesis;
		static String flaggedInterventionFlagRadiotherapy;
		static String flaggedInterventionFlagTracheostomy;
		static String flaggedInterventionFlagVascularAccessDevice;
		static String flaggedInterventionFlagBiopsy;
		static String flaggedInterventionFlagEndoscopy;
		static String oohPTCAFlag;
		static String oohCardiacCathFlag;
		static String oohPaceMakerImplantFlag;
		static String cmgReturnCode;
		static String cacsReturnCode;
		static String cmgAgeCategoryReturnCode;
		static String coMorbidityReturnCode;
		static String flaggedInterventionReturnCode;
		static String interventionEventReturnCode;
		static String interventionOOHReturnCode;
		static String elosReturnCode;
		static String mac;
		static String cacsPartition;
		static String cacsBranchCode;
		static String cacsLogicTypeCode;
		static String cacsAgeCategory;
		static String cacsInvestigativeTechnologyTotalCount;
		static String cacsInvestigativeTechnologyCategory1;
		static String cacsInvestigativeTechnologyCategory1Count;
		static String cacsInvestigativeTechnologyCategory2;
		static String cacsInvestigativeTechnologyCategory2Count;
		static String cacsInvestigativeTechnologyCategory3;
		static String cacsInvestigativeTechnologyCategory3Count;
		static String cacsInvestigativeTechnologyCategory4;
		static String cacsInvestigativeTechnologyCategory4Count;
		static String cacsInvestigativeTechnologyCategory5;
		static String cacsInvestigativeTechnologyCategory5Count;
		static String cacsInvestigativeTechnologyCategory6;
		static String cacsInvestigativeTechnologyCategory6Count;
		static String cacsInvestigativeTechnologyCategory7;
		static String cacsInvestigativeTechnologyCategory7Count;
		static String cacsInvestigativeTechnologyCategory8;
		static String cacsInvestigativeTechnologyCategory8Count;
		static String cacsInvestigativeTechnologyCategory9;
		static String cacsInvestigativeTechnologyCategory9Count;
		static String cacsInvestigativeTechnologyCategory10;
		static String cacsInvestigativeTechnologyCategory10Count;
		static String cacsRIWReturnCode;
		static String cacsAgeCategoryReturnCode;
		static String cacsAnaestheticReturnCode;
		static String cacsInvestigativeTechnologyReturnCode;
		static String coMorbidityCountCode;
		static String filler2;
		static String forInternalCIHIUse;
		static String flaggedInterventionFlagECMO;
		static String inpatientTypicalRIWValue;
		static String everythingElse;
		static String admitDate;
		static String dischargeDate;
		static String oohProcedureCategory;
		static String stayType;
		static String programArea;
		static String ambulatoryVisitIntensityIndicator;
		static String ambulatoryCareTypeCode;
		
		/*
		 * Update the int/begin indexes to have the correct value stored
		 * based on which grouper you are converting the data for.
		 */
		public static void parseLine(String line){
			testCaseIdentifier = line.substring(0,11);
			methodologyYear = line.substring(11,15);
			reportingFacilityAmbCareNumber = line.substring(15,20);
			fiscalYear = line.substring(20,24);
			fiscalPeriod = line.substring(24,26);
			abstractNumber = line.substring(26,33);
			//batchNumber = line.substring(27, 29);
			ageCode = line.substring(33,34);
			ageNumber = line.substring(34,37);
			gender = line.substring(37,38);
			stayType = line.substring(38,39);
			dischargeDisposition = line.substring(39,41);
			programArea = line.substring(41,43) ;
			ambulatoryVisitIntensityIndicator = line.substring(43,44);
			ambulatoryCareTypeCode = line.substring(44,46);
			dx1Code = line.substring(46,53);
			dx2Code = line.substring(53,60);
			dx3Code = line.substring(60,67);
			dx4Code = line.substring(67,74);
			dx5Code = line.substring(74,81);
			dx6Code = line.substring(81,88);
			dx7Code = line.substring(88,95);
			dx8Code = line.substring(95,102);
			dx9Code = line.substring(102,109);
			dx10Code = line.substring(109,116);
			//totalLOS = line.substring(55,60);
			//acuteLOS = line.substring(60,65);
			//codingClassificationSystem = line.substring(65,66);
			interventionCode1 = line.substring(116,126);
			statusAttributeCode1 = line.substring(126,128);
			locationAttributeCode1 = line.substring(128,130);
			extentAttribute1 = line.substring(130,132);
			oohIndicator1 = line.substring(132,133);
			interventionCode2 = line.substring(133,143);
			statusAttributeCode2 = line.substring(143,145);
			locationAttributeCode2 = line.substring(145,147);
			extentAttribute2 = line.substring(147,149);
			oohIndicator2 = line.substring(149,150);
			interventionCode3 = line.substring(150,160);
			statusAttributeCode3 = line.substring(160,162);
			locationAttributeCode3 = line.substring(162,164);
			extentAttribute3 = line.substring(164,166);
			oohIndicator3 = line.substring(166,167);
			interventionCode4 = line.substring(167,177);
			statusAttributeCode4 = line.substring(177,179);
			locationAttributeCode4 = line.substring(179,181);
			extentAttribute4 = line.substring(181,183);
			oohIndicator4 = line.substring(183,184);
			interventionCode5 = line.substring(184,194);
			statusAttributeCode5 = line.substring(194,196);
			locationAttributeCode5 = line.substring(196,198);
			extentAttribute5 = line.substring(198,200);
			oohIndicator5 = line.substring(200,201);
			interventionCode6 = line.substring(201,211);
			statusAttributeCode6 = line.substring(211,213);
			locationAttributeCode6 = line.substring(213,215);
			extentAttribute6 = line.substring(215,217);
			oohIndicator6 = line.substring(217,218);
			interventionCode7 = line.substring(218,228);
			statusAttributeCode7 = line.substring(228,230);
			locationAttributeCode7 = line.substring(230,232);
			extentAttribute7 = line.substring(232,234);
			oohIndicator7 = line.substring(234,235);
			interventionCode8 = line.substring(235,245);
			statusAttributeCode8 = line.substring(245,247);
			locationAttributeCode8 = line.substring(247,249);
			extentAttribute8 = line.substring(249,251);
			oohIndicator8 = line.substring(251,252);
			interventionCode9 = line.substring(252,262);
			statusAttributeCode9 = line.substring(262,264);
			locationAttributeCode9 = line.substring(264,266);
			extentAttribute9 = line.substring(266,268);
			oohIndicator9 = line.substring(268,269);
			interventionCode10 = line.substring(269,279);
			statusAttributeCode10 = line.substring(279,281);
			locationAttributeCode10 = line.substring(281,283);
			extentAttribute10 = line.substring(283,285);
			oohIndicator10 = line.substring(285,286);
			anaestheticTechnique1 = line.substring(286,287);
			anaestheticTechnique2 = line.substring(287,288);
			anaestheticTechnique3 = line.substring(288,289);
			anaestheticTechnique4 = line.substring(289,290);
			anaestheticTechnique5 = line.substring(290,291);
			mac = line.substring(291,293);
			CACS = line.substring(293,297);
			CACSRIW = line.substring(297,306);
			cacsAgeCategory = line.substring(306,307);
			CACSAnaestheticCode = line.substring(307,308);
			cacsInvestigativeTechnologyTotalCount = line.substring(308,310);
			cacsPartition = line.substring(310,311);
			interventionUsedForCACSAssignment = line.substring(311,321);
			statusAttributeUsedForCACSAssignment = line.substring(321,323);
			locationAttributeUsedForCACSAssignment = line.substring(323,325);
			extentAttributeUsedForCACSAssignment = line.substring(325,327);
			cacsBranchCode = line.substring(327,330);
			cacsLogicTypeCode = line.substring(330,331);
			cacsReturnCode = line.substring(331,333);
			cacsAgeCategoryReturnCode = line.substring(333,335);
			cacsAnaestheticReturnCode = line.substring(335,337);
			cacsInvestigativeTechnologyReturnCode = line.substring(337,339);
			cacsRIWReturnCode = line.substring(339,341);
			cacsInvestigativeTechnologyCategory1 = line.substring(341,343);
			cacsInvestigativeTechnologyCategory1Count = line.substring(343,344);
			cacsInvestigativeTechnologyCategory2 = line.substring(344,346);
			cacsInvestigativeTechnologyCategory2Count = line.substring(346,347);
			cacsInvestigativeTechnologyCategory3 = line.substring(347,349);
			cacsInvestigativeTechnologyCategory3Count = line.substring(349,350);
			cacsInvestigativeTechnologyCategory4 = line.substring(350,352);
			cacsInvestigativeTechnologyCategory4Count = line.substring(352,353);
			cacsInvestigativeTechnologyCategory5 = line.substring(353,355);
			cacsInvestigativeTechnologyCategory5Count = line.substring(355,356);
			cacsInvestigativeTechnologyCategory6 = line.substring(356,358);
			cacsInvestigativeTechnologyCategory6Count = line.substring(358,359);
			cacsInvestigativeTechnologyCategory7 = line.substring(359,361);
			cacsInvestigativeTechnologyCategory7Count = line.substring(361,362);
			cacsInvestigativeTechnologyCategory8 = line.substring(362,364);
			cacsInvestigativeTechnologyCategory8Count = line.substring(364,365);
			cacsInvestigativeTechnologyCategory9 = line.substring(365,367);
			cacsInvestigativeTechnologyCategory9Count = line.substring(367,368);
			cacsInvestigativeTechnologyCategory10 = line.substring(368,370);
			cacsInvestigativeTechnologyCategory10Count = line.substring(370,371);
			//below can be modified, adding possible value because the 2015/2016 data contains these values in template, even though empty
			admitDate = "          ";
			dischargeDate = "          ";
						
		}
		
		/*
		 * Organize the data for output file
		 */
		public static void organizeForTemplate(){
			
			output = new ArrayList<String>();
			
			output.add(grouperVersionEmpty);
			output.add(admitDate);
			output.add(dischargeDate);
			output.add(ageCode);
			output.add(ageNumber);
			output.add(gender);
			output.add(stayType);
			output.add(dischargeDisposition);
			output.add(programArea);
			output.add(ambulatoryVisitIntensityIndicator);
			output.add(ambulatoryCareTypeCode);
			output.add(dx1Code);
			output.add(dx2Code);
			output.add(dx3Code);
			output.add(dx4Code);
			output.add(dx5Code);
			output.add(dx6Code);
			output.add(dx7Code);
			output.add(dx8Code);
			output.add(dx9Code);
			output.add(dx10Code);
			output.add(interventionCode1);
			output.add(interventionCode2);
			output.add(interventionCode3);
			output.add(interventionCode4);
			output.add(interventionCode5);
			output.add(interventionCode6);
			output.add(interventionCode7);
			output.add(interventionCode8);
			output.add(interventionCode9);
			output.add(interventionCode10);
			output.add(statusAttributeCode1);
			output.add(statusAttributeCode2);
			output.add(statusAttributeCode3);
			output.add(statusAttributeCode4);
			output.add(statusAttributeCode5);
			output.add(statusAttributeCode6);
			output.add(statusAttributeCode7);
			output.add(statusAttributeCode8);
			output.add(statusAttributeCode9);
			output.add(statusAttributeCode10);
			output.add(locationAttributeCode1);
			output.add(locationAttributeCode2);
			output.add(locationAttributeCode3);
			output.add(locationAttributeCode4);
			output.add(locationAttributeCode5);
			output.add(locationAttributeCode6);
			output.add(locationAttributeCode7);
			output.add(locationAttributeCode8);
			output.add(locationAttributeCode9);
			output.add(locationAttributeCode10);
			output.add(extentAttribute1);
			output.add(extentAttribute2);
			output.add(extentAttribute3);
			output.add(extentAttribute4);
			output.add(extentAttribute5);
			output.add(extentAttribute6);
			output.add(extentAttribute7);
			output.add(extentAttribute8);
			output.add(extentAttribute9);
			output.add(extentAttribute10);
			output.add(oohIndicator1);
			output.add(oohIndicator2);
			output.add(oohIndicator3);
			output.add(oohIndicator4);
			output.add(oohIndicator5);
			output.add(oohIndicator6);
			output.add(oohIndicator7);
			output.add(oohIndicator8);
			output.add(oohIndicator9);
			output.add(oohIndicator10);
			output.add(anaestheticTechnique1);
			output.add(anaestheticTechnique2);
			output.add(anaestheticTechnique3);
			output.add(anaestheticTechnique4);
			output.add(anaestheticTechnique5);
		}
		
		/*
		 * Organize the data for outputExpected file
		 */
		public static void organizeExpForTemplate(){
			
			outputExp = new ArrayList<String>();
			
			outputExp.add(grouperVersionEmpty);
			outputExp.add(admitDate);
			outputExp.add(dischargeDate);
			outputExp.add(ageCode);
			outputExp.add(ageNumber);
			outputExp.add(gender);
			outputExp.add(stayType);
			outputExp.add(dischargeDisposition);
			outputExp.add(programArea);
			outputExp.add(ambulatoryVisitIntensityIndicator);
			outputExp.add(ambulatoryCareTypeCode);
			outputExp.add(dx1Code);
			outputExp.add(dx2Code);
			outputExp.add(dx3Code);
			outputExp.add(dx4Code);
			outputExp.add(dx5Code);
			outputExp.add(dx6Code);
			outputExp.add(dx7Code);
			outputExp.add(dx8Code);
			outputExp.add(dx9Code);
			outputExp.add(dx10Code);
			outputExp.add(interventionCode1);
			outputExp.add(interventionCode2);
			outputExp.add(interventionCode3);
			outputExp.add(interventionCode4);
			outputExp.add(interventionCode5);
			outputExp.add(interventionCode6);
			outputExp.add(interventionCode7);
			outputExp.add(interventionCode8);
			outputExp.add(interventionCode9);
			outputExp.add(interventionCode10);
			outputExp.add(statusAttributeCode1);
			outputExp.add(statusAttributeCode2);
			outputExp.add(statusAttributeCode3);
			outputExp.add(statusAttributeCode4);
			outputExp.add(statusAttributeCode5);
			outputExp.add(statusAttributeCode6);
			outputExp.add(statusAttributeCode7);
			outputExp.add(statusAttributeCode8);
			outputExp.add(statusAttributeCode9);
			outputExp.add(statusAttributeCode10);
			outputExp.add(locationAttributeCode1);
			outputExp.add(locationAttributeCode2);
			outputExp.add(locationAttributeCode3);
			outputExp.add(locationAttributeCode4);
			outputExp.add(locationAttributeCode5);
			outputExp.add(locationAttributeCode6);
			outputExp.add(locationAttributeCode7);
			outputExp.add(locationAttributeCode8);
			outputExp.add(locationAttributeCode9);
			outputExp.add(locationAttributeCode10);
			outputExp.add(extentAttribute1);
			outputExp.add(extentAttribute2);
			outputExp.add(extentAttribute3);
			outputExp.add(extentAttribute4);
			outputExp.add(extentAttribute5);
			outputExp.add(extentAttribute6);
			outputExp.add(extentAttribute7);
			outputExp.add(extentAttribute8);
			outputExp.add(extentAttribute9);
			outputExp.add(extentAttribute10);
			outputExp.add(oohIndicator1);
			outputExp.add(oohIndicator2);
			outputExp.add(oohIndicator3);
			outputExp.add(oohIndicator4);
			outputExp.add(oohIndicator5);
			outputExp.add(oohIndicator6);
			outputExp.add(oohIndicator7);
			outputExp.add(oohIndicator8);
			outputExp.add(oohIndicator9);
			outputExp.add(oohIndicator10);
			outputExp.add(anaestheticTechnique1);
			outputExp.add(anaestheticTechnique2);
			outputExp.add(anaestheticTechnique3);
			outputExp.add(anaestheticTechnique4);
			outputExp.add(anaestheticTechnique5);
			outputExp.add(anaestheticTechnique6);
			outputExp.add(anaestheticTechnique7);
			outputExp.add(anaestheticTechnique8);
			outputExp.add(anaestheticTechnique9);
			outputExp.add(anaestheticTechnique10);
			outputExp.add(mac);
			outputExp.add(CACS);
			outputExp.add(CACSRIW);
			outputExp.add(cacsAgeCategory);
			outputExp.add(CACSAnaestheticCode);
			outputExp.add(cacsInvestigativeTechnologyTotalCount);
			outputExp.add(cacsPartition);
			outputExp.add(interventionUsedForCACSAssignment);
			outputExp.add(statusAttributeUsedForCACSAssignment);
			outputExp.add(locationAttributeUsedForCACSAssignment);
			outputExp.add(extentAttributeUsedForCACSAssignment);
			outputExp.add(cacsBranchCode);
			outputExp.add(cacsLogicTypeCode);
			outputExp.add(cacsReturnCode);
			outputExp.add(cacsAgeCategoryReturnCode);
			outputExp.add(cacsAnaestheticReturnCode);
			outputExp.add(cacsRIWReturnCode);
			outputExp.add(cacsInvestigativeTechnologyCategory1);
			outputExp.add(cacsInvestigativeTechnologyCategory2);
			outputExp.add(cacsInvestigativeTechnologyCategory3);
			outputExp.add(cacsInvestigativeTechnologyCategory4);
			outputExp.add(cacsInvestigativeTechnologyCategory5);
			outputExp.add(cacsInvestigativeTechnologyCategory6);
			outputExp.add(cacsInvestigativeTechnologyCategory7);
			outputExp.add(cacsInvestigativeTechnologyCategory8);
			outputExp.add(cacsInvestigativeTechnologyCategory9);
			outputExp.add(cacsInvestigativeTechnologyCategory10);
			outputExp.add(cacsInvestigativeTechnologyCategory1Count);
			outputExp.add(cacsInvestigativeTechnologyCategory2Count);
			outputExp.add(cacsInvestigativeTechnologyCategory3Count);
			outputExp.add(cacsInvestigativeTechnologyCategory4Count);
			outputExp.add(cacsInvestigativeTechnologyCategory5Count);
			outputExp.add(cacsInvestigativeTechnologyCategory6Count);
			outputExp.add(cacsInvestigativeTechnologyCategory7Count);
			outputExp.add(cacsInvestigativeTechnologyCategory8Count);
			outputExp.add(cacsInvestigativeTechnologyCategory9Count);
			outputExp.add(cacsInvestigativeTechnologyCategory10Count);
			//hbam takes hbamriwvalue
		}
}
