package hig;

import java.util.ArrayList;

public class higconfig extends hig{

		static String testCaseIdentifier;
		static String methodologyYear;
		static String fiscalYear;
		static String fiscalPeriod;
		static String institutionType;
		static String institutionNumber;
		static String batchNumber;
		static String abstractNumber;
		static String ageCode;
		static String ageUnits;
		static String gender;
		static String weightInGrams;
		static String gestationalAgeAtAdmission;
		static String gestationalAgeAtDelivery;
		static String gestationalAgeAtDischarge;
		static String medicalCMG;
		static String entryCode;
		static String acuteInstitutionFromTransferIndicator;
		static String dischargeDisposition;
		static String acuteInstitutionToTransferIndicator;
		static String totalLOS;
		static String acuteLOS;
		static String codingClassificationSystem;
		static String dx1SequenceNumber;
		static String dx1Code;
		static String dx1Type;
		static String dx2SequenceNumber;
		static String dx2Code;
		static String dx2Type;
		static String dx3SequenceNumber;
		static String dx3Code;
		static String dx3Type;
		static String dx4SequenceNumber;
		static String dx4Code;
		static String dx4Type;
		static String dx5SequenceNumber;
		static String dx5Code;
		static String dx5Type;
		static String dx6SequenceNumber;
		static String dx6Code;
		static String dx6Type;
		static String dx7SequenceNumber;
		static String dx7Code;
		static String dx7Type;
		static String dx8SequenceNumber;
		static String dx8Code;
		static String dx8Type;
		static String dx9SequenceNumber;
		static String dx9Code;
		static String dx9Type;
		static String dx10SequenceNumber;
		static String dx10Code;
		static String dx10Type;
		static String dx11SequenceNumber;
		static String dx11Code;
		static String dx11Type;
		static String dx12SequenceNumber;
		static String dx12Code;
		static String dx12Type;
		static String dx13SequenceNumber;
		static String dx13Code;
		static String dx13Type;
		static String dx14SequenceNumber;
		static String dx14Code;
		static String dx14Type;
		static String dx15SequenceNumber;
		static String dx15Code;
		static String dx15Type;
		static String dx165SequenceNumber;
		static String dx16Code;
		static String dx16Type;
		static String dx17SequenceNumber;
		static String dx17Code;
		static String dx17Type;
		static String dx18SequenceNumber;
		static String dx18Code;
		static String dx18Type;
		static String dx19SequenceNumber;
		static String dx19Code;
		static String dx19Type;
		static String dx20SequenceNumber;
		static String dx20Code;
		static String dx20Type;
		static String dx21SequenceNumber;
		static String dx21Code;
		static String dx21Type;
		static String dx225SequenceNumber;
		static String dx22Code;
		static String dx22Type;
		static String dx23SequenceNumber;
		static String dx23Code;
		static String dx23Type;
		static String dx24SequenceNumber;
		static String dx24Code;
		static String dx24Type;
		static String dx25SequenceNumber;
		static String dx25Code;
		static String dx25Type;
		static String episodeSequenceNumber1;
		static String interventionWithinEpisodeSequenceNumber1;
		static String interventionCode1;
		static String statusAttributeCode1;
		static String locationAttributeCode1;
		static String extentAttribute1;
		static String anaestheticTechnique1;
		static String oohIndicator1;
		static String episodeSequenceNumber2;
		static String interventionWithinEpisodeSequenceNumber2;
		static String interventionCode2;
		static String statusAttributeCode2;
		static String locationAttributeCode2;
		static String extentAttribute2;
		static String anaestheticTechnique2;
		static String oohIndicator2;
		static String episodeSequenceNumber3;
		static String interventionWithinEpisodeSequenceNumber3;
		static String interventionCode3;
		static String statusAttributeCode3;
		static String locationAttributeCode3;
		static String extentAttribute3;
		static String anaestheticTechnique3;
		static String oohIndicator3;
		static String episodeSequenceNumber4;
		static String interventionWithinEpisodeSequenceNumber4;
		static String interventionCode4;
		static String statusAttributeCode4;
		static String locationAttributeCode4;
		static String extentAttribute4;
		static String anaestheticTechnique4;
		static String oohIndicator4;
		static String episodeSequenceNumber5;
		static String interventionWithinEpisodeSequenceNumber5;
		static String interventionCode5;
		static String statusAttributeCode5;
		static String locationAttributeCode5;
		static String extentAttribute5;
		static String anaestheticTechnique5;
		static String oohIndicator5;
		static String episodeSequenceNumber6;
		static String interventionWithinEpisodeSequenceNumber6;
		static String interventionCode6;
		static String statusAttributeCode6;
		static String locationAttributeCode6;
		static String extentAttribute6;
		static String anaestheticTechnique6;
		static String oohIndicator6;
		static String episodeSequenceNumber7;
		static String interventionWithinEpisodeSequenceNumber7;
		static String interventionCode7;
		static String statusAttributeCode7;
		static String locationAttributeCode7;
		static String extentAttribute7;
		static String anaestheticTechnique7;
		static String oohIndicator7;
		static String episodeSequenceNumber8;
		static String interventionWithinEpisodeSequenceNumber8;
		static String interventionCode8;
		static String statusAttributeCode8;
		static String locationAttributeCode8;
		static String extentAttribute8;
		static String anaestheticTechnique8;
		static String oohIndicator8;
		static String episodeSequenceNumber9;
		static String interventionWithinEpisodeSequenceNumber9;
		static String interventionCode9;
		static String statusAttributeCode9;
		static String locationAttributeCode9;
		static String extentAttribute9;
		static String anaestheticTechnique9;
		static String oohIndicator9;
		static String episodeSequenceNumber10;
		static String interventionWithinEpisodeSequenceNumber10;
		static String interventionCode10;
		static String statusAttributeCode10;
		static String locationAttributeCode10;
		static String extentAttribute10;
		static String anaestheticTechnique10;
		static String oohIndicator10;
		static String episodeSequenceNumber11;
		static String interventionWithinEpisodeSequenceNumber11;
		static String interventionCode11;
		static String statusAttributeCode11;
		static String locationAttributeCode11;
		static String extentAttribute11;
		static String anaestheticTechnique11;
		static String oohIndicator11;
		static String episodeSequenceNumber12;
		static String interventionWithinEpisodeSequenceNumber12;
		static String interventionCode12;
		static String statusAttributeCode12;
		static String locationAttributeCode12;
		static String extentAttribute12;
		static String anaestheticTechnique12;
		static String oohIndicator12;
		static String episodeSequenceNumber13;
		static String interventionWithinEpisodeSequenceNumber13;
		static String interventionCode13;
		static String statusAttributeCode13;
		static String locationAttributeCode13;
		static String extentAttribute13;
		static String anaestheticTechnique13;
		static String oohIndicator13;
		static String episodeSequenceNumber14;
		static String interventionWithinEpisodeSequenceNumber14;
		static String interventionCode14;
		static String statusAttributeCode14;
		static String locationAttributeCode14;
		static String extentAttribute14;
		static String anaestheticTechnique14;
		static String oohIndicator14;
		static String episodeSequenceNumber15;
		static String interventionWithinEpisodeSequenceNumber15;
		static String interventionCode15;
		static String statusAttributeCode15;
		static String locationAttributeCode15;
		static String extentAttribute15;
		static String anaestheticTechnique15;
		static String oohIndicator15;
		static String episodeSequenceNumber16;
		static String interventionWithinEpisodeSequenceNumber16;
		static String interventionCode16;
		static String statusAttributeCode16;
		static String locationAttributeCode16;
		static String extentAttribute16;
		static String anaestheticTechnique16;
		static String oohIndicator16;
		static String episodeSequenceNumber17;
		static String interventionWithinEpisodeSequenceNumber17;
		static String interventionCode17;
		static String statusAttributeCode17;
		static String locationAttributeCode17;
		static String extentAttribute17;
		static String anaestheticTechnique17;
		static String oohIndicator17;
		static String episodeSequenceNumber18;
		static String interventionWithinEpisodeSequenceNumber18;
		static String interventionCode18;
		static String statusAttributeCode18;
		static String locationAttributeCode18;
		static String extentAttribute18;
		static String anaestheticTechnique18;
		static String oohIndicator18;
		static String episodeSequenceNumber19;
		static String interventionWithinEpisodeSequenceNumber19;
		static String interventionCode19;
		static String statusAttributeCode19;
		static String locationAttributeCode19;
		static String extentAttribute19;
		static String anaestheticTechnique19;
		static String oohIndicator19;
		static String episodeSequenceNumber20;
		static String interventionWithinEpisodeSequenceNumber20;
		static String interventionCode20;
		static String statusAttributeCode20;
		static String locationAttributeCode20;
		static String extentAttribute20;
		static String anaestheticTechnique20;
		static String oohIndicator20;
		static String mcc;
		static String mccPartition;
		static String mccSubPartition;
		static String cmg;
		static String coMorbidityLevel;
		static String cmgAgeCategory;
		static String coMorbidityTotalCount;
		static String flaggedInterventionStatusCode;
		static String filler;
		static String interventionEventCountCode;
		static String interventionOOHCountCode;
		static String interventionEpisodeUsedForCMGAssignment;
		static String interventionUsedForCMGAssignment;
		static String statusAttributeUsedForCMGAssignment;
		static String locationAttributeUsedForCMGAssignment;
		static String extentAttributeUsedForCMGAssignment;
		static String firstInterventionUsedForCMGSplit;
		static String statusAttributeUsedForCMGSplit;
		static String locationAttributeUsedForCMGSplit;
		static String extentAttributeUsedForCMGSplit;
		static String cmgWeightCategoryCode;
		static String dxCodeUsedForCMGAssignment;
		static String dxTypeUsedForCMGAssignment;
		static String firstdxCodeUsedInCMGSplit;
		static String inpatientRIWValue;
		static String CACS;
		static String CACSRIW;
		static String interventionUsedForCACSAssignment;
		static String statusAttributeUsedForCACSAssignment;
		static String locationAttributeUsedForCACSAssignment;
		static String extentAttributeUsedForCACSAssignment;
		static String CACSAnaestheticCode;
		static String filler1;
		static String eLOSDays;
		static String trimDays;
		static String inpatientRIWAtypicalCode;
		static String inpatientRIperdiem;
		static String inpatientRItotalfactor;
		static String inpatientRIlevel;
		static String branchCode;
		static String coMorbidityTotalFactor;
		static String flaggedInterventionFlagCardioversion;
		static String flaggedInterventionFlagChemotherapy;
		static String flaggedInterventionFlagCellSaver;
		static String flaggedInterventionFlagDialysis;
		static String flaggedInterventionFlagFeedingTube;
		static String flaggedInterventionFlagHeartResuscitation;
		static String flaggedInterventionFlagInvasiveVentilationEqualOrGreaterThan96hrs;
		static String flaggedInterventionFlagInvasiveVentilationLessThan96hrs;
		static String flaggedInterventionFlagParacentesis;
		static String flaggedInterventionFlagParenteralNutrition;
		static String flaggedInterventionFlagPleurocentesis;
		static String flaggedInterventionFlagRadiotherapy;
		static String flaggedInterventionFlagTracheostomy;
		static String flaggedInterventionFlagVascularAccessDevice;
		static String flaggedInterventionFlagBiopsy;
		static String flaggedInterventionFlagEndoscopy;
		static String oohPTCAFlag;
		static String oohCardiacCathFlag;
		static String oohPaceMakerImplantFlag;
		static String cmgReturnCode;
		static String cacsReturnCode;
		static String cmgAgeCategoryReturnCode;
		static String coMorbidityReturnCode;
		static String flaggedInterventionReturnCode;
		static String interventionEventReturnCode;
		static String interventionOOHReturnCode;
		static String elosReturnCode;
		static String mac;
		static String cacsPartition;
		static String cacsBranchCode;
		static String cacsLogicTypeCode;
		static String cacsAgeCategory;
		static String cacsInvestigativeTechnologyTotalCount;
		static String cacsInvestigativeTechnologyCategory1;
		static String cacsInvestigativeTechnologyCategory1Count;
		static String cacsInvestigativeTechnologyCategory2;
		static String cacsInvestigativeTechnologyCategory2Count;
		static String cacsInvestigativeTechnologyCategory3;
		static String cacsInvestigativeTechnologyCategory3Count;
		static String cacsInvestigativeTechnologyCategory4;
		static String cacsInvestigativeTechnologyCategory4Count;
		static String cacsInvestigativeTechnologyCategory5;
		static String cacsInvestigativeTechnologyCategory5Count;
		static String cacsInvestigativeTechnologyCategory6;
		static String cacsInvestigativeTechnologyCategory6Count;
		static String cacsInvestigativeTechnologyCategory7;
		static String cacsInvestigativeTechnologyCategory7Count;
		static String cacsInvestigativeTechnologyCategory8;
		static String cacsInvestigativeTechnologyCategory8Count;
		static String cacsInvestigativeTechnologyCategory9;
		static String cacsInvestigativeTechnologyCategory9Count;
		static String cacsInvestigativeTechnologyCategory10;
		static String cacsInvestigativeTechnologyCategory10Count;
		static String cacsRIWReturnCode;
		static String cacsAgeCategoryReturnCode;
		static String cacsAnaestheticReturnCode;
		static String cacsInvestigativeTechnologyReturnCode;
		static String coMorbidityCountCode;
		static String filler2;
		static String forInternalCIHIUse;
		static String flaggedInterventionFlagECMO;
		static String inpatientTypicalRIWValue;
		static String everythingElse;
		static String admitDate;
		static String dischargeDate;
		static String oohProcedureCategory;
		/*
		 * Update the int/begin indexes to have the correct value stored
		 * based on which grouper you are converting the data for.
		 */
		public static void parseLine(String line){
			testCaseIdentifier = line.substring(0,11);
			methodologyYear = line.substring(11,15);
			fiscalYear = line.substring(15,19);
			fiscalPeriod = line.substring(19,21);
			institutionType = line.substring(21,22);
			institutionNumber = line.substring(22,27);
			batchNumber = line.substring(27, 29);
			abstractNumber = line.substring(29, 32);
			ageCode = line.substring(32,33);
			ageUnits = line.substring(33,36);
			gender = line.substring(36,37);
			weightInGrams = line.substring(37, 41);
			gestationalAgeAtAdmission = line.substring(41,43);
			gestationalAgeAtDelivery = line.substring(43,45) ;
			gestationalAgeAtDischarge = line.substring(45,47);
			medicalCMG = line.substring(47,50);
			entryCode = line.substring(50,51);
			acuteInstitutionFromTransferIndicator = line.substring(51,52);
			dischargeDisposition = line.substring(52,54);
			acuteInstitutionToTransferIndicator = line.substring(54,55);
			totalLOS = line.substring(55,60);
			acuteLOS = line.substring(60,65);
			codingClassificationSystem = line.substring(65,66);
			dx1SequenceNumber = line.substring(66,68);
			dx1Code = line.substring(68,75);
			dx1Type = line.substring(75,76);
			dx2SequenceNumber = line.substring(76,78);
			dx2Code = line.substring(78,85);
			dx2Type = line.substring(85,86);
			dx3SequenceNumber = line.substring(86,88);
			dx3Code = line.substring(88,95);
			dx3Type = line.substring(95,96);
			dx4SequenceNumber = line.substring(96,98);
			dx4Code = line.substring(98,105);
			dx4Type = line.substring(105,106);
			dx5SequenceNumber = line.substring(106,108);
			dx5Code = line.substring(108,115);
			dx5Type = line.substring(115,116);
			dx6SequenceNumber = line.substring(116,117);
			dx6Code = line.substring(117,125);
			dx6Type = line.substring(125,126);
			dx7SequenceNumber = line.substring(126,128);
			dx7Code = line.substring(128,135);
			dx7Type = line.substring(135,136);
			dx8SequenceNumber = line.substring(136,138);
			dx8Code = line.substring(138,145);
			dx8Type = line.substring(145,146);
			dx9SequenceNumber = line.substring(146,148);
			dx9Code = line.substring(148,155);
			dx9Type = line.substring(155,156);
			dx10SequenceNumber = line.substring(156,158);
			dx10Code = line.substring(158,165);
			dx10Type = line.substring(165,166);
			dx11SequenceNumber = line.substring(166,168);
			dx11Code = line.substring(168,175);
			dx11Type = line.substring(175,176);
			dx12SequenceNumber = line.substring(176,178);
			dx12Code = line.substring(178,185);
			dx12Type = line.substring(185,186);
			dx13SequenceNumber = line.substring(186,188);
			dx13Code = line.substring(188,195);
			dx13Type = line.substring(195,196);
			dx14SequenceNumber = line.substring(196,198);
			dx14Code = line.substring(198,205);
			dx14Type = line.substring(205,206);
			dx15SequenceNumber = line.substring(206,208);
			dx15Code = line.substring(208,215);
			dx15Type = line.substring(215,216);
			dx165SequenceNumber = line.substring(216,218);
			dx16Code = line.substring(218,225);
			dx16Type = line.substring(225,226);
			dx17SequenceNumber = line.substring(226,228);
			dx17Code = line.substring(228,235);
			dx17Type = line.substring(235,236);
			dx18SequenceNumber = line.substring(236,238);
			dx18Code = line.substring(238,245);
			dx18Type = line.substring(245,246);
			dx19SequenceNumber = line.substring(246,248);
			dx19Code = line.substring(248,255);
			dx19Type = line.substring(255,256);
			dx20SequenceNumber = line.substring(256,258);
			dx20Code = line.substring(258,265);
			dx20Type = line.substring(265,266);
			dx21SequenceNumber = line.substring(266,268);
			dx21Code = line.substring(268,275);
			dx21Type = line.substring(275,276);
			dx225SequenceNumber = line.substring(276,278);
			dx22Code = line.substring(278,285);
			dx22Type = line.substring(285,286);
			dx23SequenceNumber = line.substring(286,288);
			dx23Code = line.substring(288,295);
			dx23Type = line.substring(295,296);
			dx24SequenceNumber = line.substring(296,298);
			dx24Code = line.substring(298,305);
			dx24Type = line.substring(305,306);
			dx25SequenceNumber = line.substring(306,308);
			dx25Code = line.substring(308,314);
			dx25Type = line.substring(315,316);
			episodeSequenceNumber1 = line.substring(316,318);
			interventionWithinEpisodeSequenceNumber1 = line.substring(318,320);
			interventionCode1 = line.substring(320,330);
			statusAttributeCode1 = line.substring(330,332);
			locationAttributeCode1 = line.substring(332,334);
			extentAttribute1 = line.substring(334,336);
			anaestheticTechnique1 = line.substring(336,337);
			oohIndicator1 = line.substring(337,338);
			episodeSequenceNumber2 = line.substring(338,340);
			interventionWithinEpisodeSequenceNumber2 = line.substring(340,342);
			interventionCode2 = line.substring(342,352);
			statusAttributeCode2 = line.substring(352,354);
			locationAttributeCode2 = line.substring(354,356);
			extentAttribute2 = line.substring(356,358);
			anaestheticTechnique2 = line.substring(358,359);
			oohIndicator2 = line.substring(359,360);
			episodeSequenceNumber3 = line.substring(360,362);
			interventionWithinEpisodeSequenceNumber3 = line.substring(362,364);
			interventionCode3 = line.substring(364,374);
			statusAttributeCode3 = line.substring(374,376);
			locationAttributeCode3 = line.substring(376,378);
			extentAttribute3 = line.substring(378,380);
			anaestheticTechnique3 = line.substring(380,381);
			oohIndicator3 = line.substring(381,382);
			episodeSequenceNumber4 = line.substring(382,384);
			interventionWithinEpisodeSequenceNumber4 = line.substring(384,386);
			interventionCode4 = line.substring(386,396);
			statusAttributeCode4 = line.substring(396,398);
			locationAttributeCode4 = line.substring(398,400);
			extentAttribute4 = line.substring(400,402);
			anaestheticTechnique4 = line.substring(402,403);
			oohIndicator4 = line.substring(403,404);
			episodeSequenceNumber5 = line.substring(404,406);
			interventionWithinEpisodeSequenceNumber5 = line.substring(406,408);
			interventionCode5 = line.substring(408,418);
			statusAttributeCode5 = line.substring(418,420);
			locationAttributeCode5 = line.substring(420,422);
			extentAttribute5 = line.substring(422,424);
			anaestheticTechnique5 = line.substring(424,425);
			oohIndicator5 = line.substring(425,426);
			episodeSequenceNumber6 = line.substring(426,428);
			interventionWithinEpisodeSequenceNumber6 = line.substring(428,430);
			interventionCode6 = line.substring(430,440);
			statusAttributeCode6 = line.substring(440,442);
			locationAttributeCode6 = line.substring(442,444);
			extentAttribute6 = line.substring(444,446);
			anaestheticTechnique6 = line.substring(446,447);
			oohIndicator6 = line.substring(447,448);
			episodeSequenceNumber7 = line.substring(448,450);
			interventionWithinEpisodeSequenceNumber7 = line.substring(450,452);
			interventionCode7 = line.substring(452,462);
			statusAttributeCode7 = line.substring(462,464);
			locationAttributeCode7 = line.substring(464,466);
			extentAttribute7 = line.substring(466,468);
			anaestheticTechnique7 = line.substring(468,469);
			oohIndicator7 = line.substring(469,470);
			episodeSequenceNumber8 = line.substring(470,472);
			interventionWithinEpisodeSequenceNumber8 = line.substring(472,474);
			interventionCode8 = line.substring(474,484);
			statusAttributeCode8 = line.substring(484,486);
			locationAttributeCode8 = line.substring(486,488);
			extentAttribute8 = line.substring(488,490);
			anaestheticTechnique8 = line.substring(490,491);
			oohIndicator8 = line.substring(491,492);
			episodeSequenceNumber9 = line.substring(492,494);
			interventionWithinEpisodeSequenceNumber9 = line.substring(494,496);
			interventionCode9 = line.substring(496,506);
			statusAttributeCode9 = line.substring(506,508);
			locationAttributeCode9 = line.substring(508,510);
			extentAttribute9 = line.substring(510,512);
			anaestheticTechnique9 = line.substring(512,513);
			oohIndicator9 = line.substring(513,514);
			episodeSequenceNumber10 = line.substring(514,516);
			interventionWithinEpisodeSequenceNumber10 = line.substring(516,518);
			interventionCode10 = line.substring(518,528);
			statusAttributeCode10 = line.substring(528,530);
			locationAttributeCode10 = line.substring(530,532);
			extentAttribute10 = line.substring(532,534);
			anaestheticTechnique10 = line.substring(534,535);
			oohIndicator10 = line.substring(535,536);
			episodeSequenceNumber11 = line.substring(536,538);
			interventionWithinEpisodeSequenceNumber11 = line.substring(538,540);
			interventionCode11 = line.substring(540,550);
			statusAttributeCode11 = line.substring(550,552);
			locationAttributeCode11 = line.substring(552,554);
			extentAttribute11 = line.substring(554,556);
			anaestheticTechnique11 = line.substring(556,557);
			oohIndicator11 = line.substring(557,558);
			episodeSequenceNumber12 = line.substring(558,560);
			interventionWithinEpisodeSequenceNumber12 = line.substring(560,562);
			interventionCode12 = line.substring(562,572);
			statusAttributeCode12 = line.substring(572,574);
			locationAttributeCode12 = line.substring(574,576);
			extentAttribute12 = line.substring(576,578);
			anaestheticTechnique12 = line.substring(578,579);
			oohIndicator12 = line.substring(579,580);
			episodeSequenceNumber13 = line.substring(580,582);
			interventionWithinEpisodeSequenceNumber13 = line.substring(582,584);
			interventionCode13 = line.substring(584,594);
			statusAttributeCode13 = line.substring(594,596);
			locationAttributeCode13 = line.substring(596,598);
			extentAttribute13 = line.substring(598,600);
			anaestheticTechnique13 = line.substring(600,601);
			oohIndicator13 = line.substring(601,602);
			episodeSequenceNumber14 = line.substring(602,604);
			interventionWithinEpisodeSequenceNumber14 = line.substring(604,606);
			interventionCode14 = line.substring(606,616);
			statusAttributeCode14 = line.substring(616,618);
			locationAttributeCode14 = line.substring(618,620);
			extentAttribute14 = line.substring(620,622);
			anaestheticTechnique14 = line.substring(622,623);
			oohIndicator14 = line.substring(623,624);
			episodeSequenceNumber15 = line.substring(624,626);
			interventionWithinEpisodeSequenceNumber15 = line.substring(626,628);
			interventionCode15 = line.substring(628,638);
			statusAttributeCode15 = line.substring(638,640);
			locationAttributeCode15 = line.substring(640,642);
			extentAttribute15 = line.substring(642,644);
			anaestheticTechnique15 = line.substring(644,645);
			oohIndicator15 = line.substring(645,646);
			episodeSequenceNumber16 = line.substring(646,648);
			interventionWithinEpisodeSequenceNumber16 = line.substring(648,650);
			interventionCode16 = line.substring(650,660);
			statusAttributeCode16 = line.substring(660,662);
			locationAttributeCode16 = line.substring(662,663);
			extentAttribute16 = line.substring(663,665);
			anaestheticTechnique16 = line.substring(665,666);
			oohIndicator16 = line.substring(666,667);
			episodeSequenceNumber17 = line.substring(667,669);
			interventionWithinEpisodeSequenceNumber17 = line.substring(669,671);
			interventionCode17 = line.substring(671,681);
			statusAttributeCode17 = line.substring(681,683);
			locationAttributeCode17 = line.substring(683,685);
			extentAttribute17 = line.substring(685,687);
			anaestheticTechnique17 = line.substring(688,689);
			oohIndicator17 = line.substring(689,690);
			episodeSequenceNumber18 = line.substring(690,692);
			interventionWithinEpisodeSequenceNumber18 = line.substring(692,694);
			interventionCode18 = line.substring(694,704);
			statusAttributeCode18 = line.substring(704,706);
			locationAttributeCode18 = line.substring(706,708);
			extentAttribute18 = line.substring(708,710);
			anaestheticTechnique18 = line.substring(710,711);
			oohIndicator18 = line.substring(711,712);
			episodeSequenceNumber19 = line.substring(712,714);
			interventionWithinEpisodeSequenceNumber19 = line.substring(714,716);
			interventionCode19 = line.substring(716,726);
			statusAttributeCode19 = line.substring(726,728);
			locationAttributeCode19 = line.substring(728,730);
			extentAttribute19 = line.substring(730,732);
			anaestheticTechnique19 = line.substring(732,733);
			oohIndicator19 = line.substring(733,734);
			episodeSequenceNumber20 = line.substring(734,736);
			interventionWithinEpisodeSequenceNumber20 = line.substring(736,738);
			interventionCode20 = line.substring(738,748);
			statusAttributeCode20 = line.substring(748,750);
			locationAttributeCode20 = line.substring(750,752);
			extentAttribute20 = line.substring(752,754);
			anaestheticTechnique20 = line.substring(754,755);
			oohIndicator20 = line.substring(755,756);
			mcc = line.substring(756,758);
			mccPartition = line.substring(758,759);
			mccSubPartition = line.substring(759,760);
			cmg = line.substring(760,763);
			coMorbidityLevel = line.substring(763,764);
			cmgAgeCategory = line.substring(764,765);
			coMorbidityTotalCount = line.substring(765,767);
			flaggedInterventionStatusCode = line.substring(767,768);
			filler = line.substring(768,770);
			interventionEventCountCode = line.substring(770,771);
			interventionOOHCountCode = line.substring(771,772);
			interventionEpisodeUsedForCMGAssignment = line.substring(772,774);
			interventionUsedForCMGAssignment = line.substring(774,784);
			statusAttributeUsedForCMGAssignment = line.substring(784,786);
			locationAttributeUsedForCMGAssignment = line.substring(786,788);
			extentAttributeUsedForCMGAssignment = line.substring(788,790);
			firstInterventionUsedForCMGSplit = line.substring(790,800);
			statusAttributeUsedForCMGSplit = line.substring(800,802);
			locationAttributeUsedForCMGSplit = line.substring(802,804);
			extentAttributeUsedForCMGSplit = line.substring(804,806);
			cmgWeightCategoryCode = line.substring(806,807);
			dxCodeUsedForCMGAssignment = line.substring(807,814);
			dxTypeUsedForCMGAssignment = line.substring(814,815);
			firstdxCodeUsedInCMGSplit = line.substring(815,822);
			inpatientRIWValue = line.substring(822,831);
			CACS = line.substring(831,835);
			CACSRIW = line.substring(835,844);
			interventionUsedForCACSAssignment = line.substring(844,854);
			statusAttributeUsedForCACSAssignment = line.substring(854,856);
			locationAttributeUsedForCACSAssignment = line.substring(856,858);
			extentAttributeUsedForCACSAssignment = line.substring(858,860);
			CACSAnaestheticCode = line.substring(860,861);
			filler1 = line.substring(861,862);
			eLOSDays = line.substring(862,867);
			trimDays = line.substring(867,870);
			inpatientRIWAtypicalCode = line.substring(870,872);
			inpatientRIperdiem = line.substring(872,880);
			inpatientRItotalfactor = line.substring(880,889);
			inpatientRIlevel = line.substring(889,890);
			branchCode = line.substring(890,892);
			coMorbidityTotalFactor = line.substring(892,901);
			flaggedInterventionFlagCardioversion = line.substring(901,902);
			flaggedInterventionFlagCellSaver = line.substring(902,903);
			flaggedInterventionFlagChemotherapy = line.substring(903,904);
			flaggedInterventionFlagDialysis = line.substring(904,905);
			flaggedInterventionFlagFeedingTube = line.substring(905,906);
			flaggedInterventionFlagHeartResuscitation = line.substring(906,907);
			flaggedInterventionFlagInvasiveVentilationEqualOrGreaterThan96hrs = line.substring(907,908);
			flaggedInterventionFlagInvasiveVentilationLessThan96hrs = line.substring(908,909);
			flaggedInterventionFlagParacentesis = line.substring(909,910);
			flaggedInterventionFlagParenteralNutrition = line.substring(910,911);
			flaggedInterventionFlagPleurocentesis = line.substring(911,912);
			flaggedInterventionFlagRadiotherapy = line.substring(912,913);
			flaggedInterventionFlagTracheostomy = line.substring(913,914);
			flaggedInterventionFlagVascularAccessDevice = line.substring(914,915);
			flaggedInterventionFlagBiopsy = line.substring(915,916);
			flaggedInterventionFlagEndoscopy = line.substring(916,917);
			oohPTCAFlag = line.substring(917,918);
			oohCardiacCathFlag = line.substring(918,919);
			oohPaceMakerImplantFlag = line.substring(919,920);
			cmgReturnCode = line.substring(920,922);
			cacsReturnCode = line.substring(922,924);
			cmgAgeCategoryReturnCode = line.substring(924,926);
			coMorbidityReturnCode = line.substring(926,928);
			flaggedInterventionReturnCode = line.substring(928,930);
			interventionEventReturnCode = line.substring(930,932);
			interventionOOHReturnCode = line.substring(932,934);
			elosReturnCode = line.substring(934,936);
			mac = line.substring(936,938);
			cacsPartition = line.substring(938,939);
			cacsBranchCode = line.substring(939,942);
			cacsLogicTypeCode = line.substring(942,943);
			cacsAgeCategory = line.substring(943,944);
			cacsInvestigativeTechnologyTotalCount = line.substring(944,946);
			cacsInvestigativeTechnologyCategory1 = line.substring(946,948);
			cacsInvestigativeTechnologyCategory1Count = line.substring(948,949);
			cacsInvestigativeTechnologyCategory2 = line.substring(949,951);
			cacsInvestigativeTechnologyCategory2Count = line.substring(951,952);
			cacsInvestigativeTechnologyCategory3 = line.substring(952,954);
			cacsInvestigativeTechnologyCategory3Count = line.substring(954,955);
			cacsInvestigativeTechnologyCategory4 = line.substring(955,957);
			cacsInvestigativeTechnologyCategory4Count = line.substring(957,958);
			cacsInvestigativeTechnologyCategory5 = line.substring(958,960);
			cacsInvestigativeTechnologyCategory5Count = line.substring(960,961);
			cacsInvestigativeTechnologyCategory6 = line.substring(961,963);
			cacsInvestigativeTechnologyCategory6Count = line.substring(963,964);
			cacsInvestigativeTechnologyCategory7 = line.substring(964,966);
			cacsInvestigativeTechnologyCategory7Count = line.substring(966,967);
			cacsInvestigativeTechnologyCategory8 = line.substring(967,969);
			cacsInvestigativeTechnologyCategory8Count = line.substring(969,970);
			cacsInvestigativeTechnologyCategory9 = line.substring(970,972);
			cacsInvestigativeTechnologyCategory9Count = line.substring(972,973);
			cacsInvestigativeTechnologyCategory10 = line.substring(973,975);
			cacsInvestigativeTechnologyCategory10Count = line.substring(975,976);
			cacsRIWReturnCode = line.substring(976,978);
			cacsAgeCategoryReturnCode = line.substring(978,980);
			cacsAnaestheticReturnCode = line.substring(980,982);
			cacsInvestigativeTechnologyReturnCode = line.substring(982,984);
			coMorbidityCountCode = line.substring(984,985);
			filler2 = line.substring(985,986);
			forInternalCIHIUse = line.substring(986,997);
			flaggedInterventionFlagECMO = line.substring(997,998);
			inpatientTypicalRIWValue = line.substring(998,1007);
			everythingElse = line.substring(698, 1007);
			admitDate = ("");
			dischargeDate = ("");
			oohProcedureCategory = (" ");
			
		}
		
		/*
		 * Organize the data for output file
		 */
		public static void organizeForTemplate(){
			
			output = new ArrayList<String>();
			
			output.add(testCaseIdentifier);
			output.add(methodologyYear);
			output.add(institutionType);
			output.add(ageCode);
			output.add(ageUnits);
			output.add(gender);
			output.add(weightInGrams);
			output.add(gestationalAgeAtDelivery);
			output.add(medicalCMG);
			output.add(entryCode);
			output.add(dischargeDisposition);
			output.add(totalLOS);
			output.add(acuteLOS);
			output.add(codingClassificationSystem);
			output.add(dx1Code);
			output.add(dx2Code);
			output.add(dx3Code);
			output.add(dx4Code);
			output.add(dx5Code);
			output.add(dx6Code);
			output.add(dx7Code);
			output.add(dx8Code);
			output.add(dx9Code);
			output.add(dx10Code);
			output.add(dx11Code);
			output.add(dx12Code);
			output.add(dx13Code);
			output.add(dx14Code);
			output.add(dx15Code);
			output.add(dx16Code);
			output.add(dx17Code);
			output.add(dx18Code);
			output.add(dx19Code);
			output.add(dx20Code);
			output.add(dx21Code);
			output.add(dx22Code);
			output.add(dx23Code);
			output.add(dx24Code);
			output.add(dx25Code);
			output.add(dx1Type);
			output.add(dx2Type);
			output.add(dx3Type);
			output.add(dx4Type);
			output.add(dx5Type);
			output.add(dx6Type);	
			output.add(dx7Type);
			output.add(dx8Type);
			output.add(dx9Type);
			output.add(dx10Type);
			output.add(dx11Type);
			output.add(dx12Type);
			output.add(dx13Type);
			output.add(dx14Type);
			output.add(dx15Type);
			output.add(dx16Type);
			output.add(dx17Type);
			output.add(dx18Type);
			output.add(dx19Type);
			output.add(dx20Type);
			output.add(dx21Type);
			output.add(dx22Type);
			output.add(dx23Type);
			output.add(dx24Type);
			output.add(dx25Type);
			output.add(episodeSequenceNumber1);
			output.add(episodeSequenceNumber2);
			output.add(episodeSequenceNumber3);
			output.add(episodeSequenceNumber4);
			output.add(episodeSequenceNumber5);
			output.add(episodeSequenceNumber6);
			output.add(episodeSequenceNumber7);
			output.add(episodeSequenceNumber8);
			output.add(episodeSequenceNumber9);
			output.add(episodeSequenceNumber10);
			output.add(episodeSequenceNumber11);
			output.add(episodeSequenceNumber12);
			output.add(episodeSequenceNumber13);
			output.add(episodeSequenceNumber14);
			output.add(episodeSequenceNumber15);
			output.add(episodeSequenceNumber16);
			output.add(episodeSequenceNumber17);
			output.add(episodeSequenceNumber18);
			output.add(episodeSequenceNumber19);
			output.add(episodeSequenceNumber20);
			output.add(interventionWithinEpisodeSequenceNumber1);
			output.add(interventionWithinEpisodeSequenceNumber2);
			output.add(interventionWithinEpisodeSequenceNumber3);
			output.add(interventionWithinEpisodeSequenceNumber4);
			output.add(interventionWithinEpisodeSequenceNumber5);
			output.add(interventionWithinEpisodeSequenceNumber6);
			output.add(interventionWithinEpisodeSequenceNumber7);
			output.add(interventionWithinEpisodeSequenceNumber8);
			output.add(interventionWithinEpisodeSequenceNumber9);
			output.add(interventionWithinEpisodeSequenceNumber10);
			output.add(interventionWithinEpisodeSequenceNumber11);
			output.add(interventionWithinEpisodeSequenceNumber12);
			output.add(interventionWithinEpisodeSequenceNumber13);
			output.add(interventionWithinEpisodeSequenceNumber14);
			output.add(interventionWithinEpisodeSequenceNumber15);
			output.add(interventionWithinEpisodeSequenceNumber16);
			output.add(interventionWithinEpisodeSequenceNumber17);
			output.add(interventionWithinEpisodeSequenceNumber18);
			output.add(interventionWithinEpisodeSequenceNumber19);
			output.add(interventionWithinEpisodeSequenceNumber20);
			output.add(interventionCode1);
			output.add(interventionCode2);
			output.add(interventionCode3);
			output.add(interventionCode4);
			output.add(interventionCode5);
			output.add(interventionCode6);
			output.add(interventionCode7);
			output.add(interventionCode8);
			output.add(interventionCode9);
			output.add(interventionCode10);
			output.add(interventionCode11);
			output.add(interventionCode12);
			output.add(interventionCode13);
			output.add(interventionCode14);
			output.add(interventionCode15);
			output.add(interventionCode16);
			output.add(interventionCode17);
			output.add(interventionCode18);
			output.add(interventionCode19);
			output.add(interventionCode20);
			output.add(statusAttributeCode1);
			output.add(statusAttributeCode2);
			output.add(statusAttributeCode3);
			output.add(statusAttributeCode4);
			output.add(statusAttributeCode5);
			output.add(statusAttributeCode6);
			output.add(statusAttributeCode7);
			output.add(statusAttributeCode8);
			output.add(statusAttributeCode9);
			output.add(statusAttributeCode10);
			output.add(statusAttributeCode11);
			output.add(statusAttributeCode12);
			output.add(statusAttributeCode13);
			output.add(statusAttributeCode14);
			output.add(statusAttributeCode15);
			output.add(statusAttributeCode16);
			output.add(statusAttributeCode17);
			output.add(statusAttributeCode18);
			output.add(statusAttributeCode19);
			output.add(statusAttributeCode20);
			output.add(locationAttributeCode1);
			output.add(locationAttributeCode2);
			output.add(locationAttributeCode3);
			output.add(locationAttributeCode4);
			output.add(locationAttributeCode5);
			output.add(locationAttributeCode6);
			output.add(locationAttributeCode7);
			output.add(locationAttributeCode8);
			output.add(locationAttributeCode9);
			output.add(locationAttributeCode10);
			output.add(locationAttributeCode11);
			output.add(locationAttributeCode12);
			output.add(locationAttributeCode13);
			output.add(locationAttributeCode14);
			output.add(locationAttributeCode15);
			output.add(locationAttributeCode16);
			output.add(locationAttributeCode17);
			output.add(locationAttributeCode18);
			output.add(locationAttributeCode19);
			output.add(locationAttributeCode20);
			output.add(extentAttribute1);
			output.add(extentAttribute2);
			output.add(extentAttribute3);
			output.add(extentAttribute4);
			output.add(extentAttribute5);
			output.add(extentAttribute6);
			output.add(extentAttribute7);
			output.add(extentAttribute8);
			output.add(extentAttribute9);
			output.add(extentAttribute10);
			output.add(extentAttribute11);
			output.add(extentAttribute12);
			output.add(extentAttribute13);
			output.add(extentAttribute14);
			output.add(extentAttribute15);
			output.add(extentAttribute16);
			output.add(extentAttribute17);
			output.add(extentAttribute18);
			output.add(extentAttribute19);
			output.add(extentAttribute20);
			output.add(anaestheticTechnique1);
			output.add(anaestheticTechnique2);
			output.add(anaestheticTechnique3);
			output.add(anaestheticTechnique4);
			output.add(anaestheticTechnique5);
			output.add(anaestheticTechnique6);
			output.add(anaestheticTechnique7);
			output.add(anaestheticTechnique8);
			output.add(anaestheticTechnique9);
			output.add(anaestheticTechnique10);
			output.add(anaestheticTechnique11);
			output.add(anaestheticTechnique12);
			output.add(anaestheticTechnique13);
			output.add(anaestheticTechnique14);
			output.add(anaestheticTechnique15);
			output.add(anaestheticTechnique16);
			output.add(anaestheticTechnique17);
			output.add(anaestheticTechnique18);
			output.add(anaestheticTechnique19);
			output.add(anaestheticTechnique20);
			output.add(oohIndicator1);
			output.add(oohIndicator2);
			output.add(oohIndicator3);
			output.add(oohIndicator4);
			output.add(oohIndicator5);
			output.add(oohIndicator6);
			output.add(oohIndicator7);
			output.add(oohIndicator8);
			output.add(oohIndicator9);
			output.add(oohIndicator10);
			output.add(oohIndicator11);
			output.add(oohIndicator12);
			output.add(oohIndicator13);
			output.add(oohIndicator14);
			output.add(oohIndicator15);
			output.add(oohIndicator16);
			output.add(oohIndicator17);
			output.add(oohIndicator18);
			output.add(oohIndicator19);
			output.add(oohIndicator20);
			output.add(mcc);
			output.add(mccPartition);
			output.add(mccSubPartition);
			output.add(cmg);
			output.add(coMorbidityLevel);
			output.add(flaggedInterventionStatusCode);
			output.add(interventionEventCountCode);
			output.add(interventionOOHCountCode);
			output.add(interventionEpisodeUsedForCMGAssignment);
			//output.add(everythingElse);
			//only in output it appears - output.add(grouperVersion);
		}
		
		/*
		 * Organize the data for outputExpected file
		 */
		public static void organizeExpForTemplate(){
			
			outputExp = new ArrayList<String>();
			
			outputExp.add(testCaseIdentifier);
			outputExp.add(methodologyYear);
			outputExp.add(institutionType);
			outputExp.add(ageCode);
			outputExp.add(ageUnits);
			outputExp.add(gender);
			outputExp.add(weightInGrams);
			outputExp.add(gestationalAgeAtDelivery);
			outputExp.add(medicalCMG);
			outputExp.add(entryCode);
			outputExp.add(dischargeDisposition);
			outputExp.add(totalLOS);
			outputExp.add(acuteLOS);
			outputExp.add(codingClassificationSystem);
			outputExp.add(dx1Code);
			outputExp.add(dx2Code);
			outputExp.add(dx3Code);
			outputExp.add(dx4Code);
			outputExp.add(dx5Code);
			outputExp.add(dx6Code);
			outputExp.add(dx7Code);
			outputExp.add(dx8Code);
			outputExp.add(dx9Code);
			outputExp.add(dx10Code);
			outputExp.add(dx11Code);
			outputExp.add(dx12Code);
			outputExp.add(dx13Code);
			outputExp.add(dx14Code);
			outputExp.add(dx15Code);
			outputExp.add(dx16Code);
			outputExp.add(dx17Code);
			outputExp.add(dx18Code);
			outputExp.add(dx19Code);
			outputExp.add(dx20Code);
			outputExp.add(dx21Code);
			outputExp.add(dx22Code);
			outputExp.add(dx23Code);
			outputExp.add(dx24Code);
			outputExp.add(dx25Code);
			outputExp.add(dx1Type);
			outputExp.add(dx2Type);
			outputExp.add(dx3Type);
			outputExp.add(dx4Type);
			outputExp.add(dx5Type);
			outputExp.add(dx6Type);	
			outputExp.add(dx7Type);
			outputExp.add(dx8Type);
			outputExp.add(dx9Type);
			outputExp.add(dx10Type);
			outputExp.add(dx11Type);
			outputExp.add(dx12Type);
			outputExp.add(dx13Type);
			outputExp.add(dx14Type);
			outputExp.add(dx15Type);
			outputExp.add(dx16Type);
			outputExp.add(dx17Type);
			outputExp.add(dx18Type);
			outputExp.add(dx19Type);
			outputExp.add(dx20Type);
			outputExp.add(dx21Type);
			outputExp.add(dx22Type);
			outputExp.add(dx23Type);
			outputExp.add(dx24Type);
			outputExp.add(dx25Type);
			outputExp.add(episodeSequenceNumber1);
			outputExp.add(episodeSequenceNumber2);
			outputExp.add(episodeSequenceNumber3);
			outputExp.add(episodeSequenceNumber4);
			outputExp.add(episodeSequenceNumber5);
			outputExp.add(episodeSequenceNumber6);
			outputExp.add(episodeSequenceNumber7);
			outputExp.add(episodeSequenceNumber8);
			outputExp.add(episodeSequenceNumber9);
			outputExp.add(episodeSequenceNumber10);
			outputExp.add(episodeSequenceNumber11);
			outputExp.add(episodeSequenceNumber12);
			outputExp.add(episodeSequenceNumber13);
			outputExp.add(episodeSequenceNumber14);
			outputExp.add(episodeSequenceNumber15);
			outputExp.add(episodeSequenceNumber16);
			outputExp.add(episodeSequenceNumber17);
			outputExp.add(episodeSequenceNumber18);
			outputExp.add(episodeSequenceNumber19);
			outputExp.add(episodeSequenceNumber20);
			outputExp.add(interventionWithinEpisodeSequenceNumber1);
			outputExp.add(interventionWithinEpisodeSequenceNumber2);
			outputExp.add(interventionWithinEpisodeSequenceNumber3);
			outputExp.add(interventionWithinEpisodeSequenceNumber4);
			outputExp.add(interventionWithinEpisodeSequenceNumber5);
			outputExp.add(interventionWithinEpisodeSequenceNumber6);
			outputExp.add(interventionWithinEpisodeSequenceNumber7);
			outputExp.add(interventionWithinEpisodeSequenceNumber8);
			outputExp.add(interventionWithinEpisodeSequenceNumber9);
			outputExp.add(interventionWithinEpisodeSequenceNumber10);
			outputExp.add(interventionWithinEpisodeSequenceNumber11);
			outputExp.add(interventionWithinEpisodeSequenceNumber12);
			outputExp.add(interventionWithinEpisodeSequenceNumber13);
			outputExp.add(interventionWithinEpisodeSequenceNumber14);
			outputExp.add(interventionWithinEpisodeSequenceNumber15);
			outputExp.add(interventionWithinEpisodeSequenceNumber16);
			outputExp.add(interventionWithinEpisodeSequenceNumber17);
			outputExp.add(interventionWithinEpisodeSequenceNumber18);
			outputExp.add(interventionWithinEpisodeSequenceNumber19);
			outputExp.add(interventionWithinEpisodeSequenceNumber20);
			outputExp.add(interventionCode1);
			outputExp.add(interventionCode2);
			outputExp.add(interventionCode3);
			outputExp.add(interventionCode4);
			outputExp.add(interventionCode5);
			outputExp.add(interventionCode6);
			outputExp.add(interventionCode7);
			outputExp.add(interventionCode8);
			outputExp.add(interventionCode9);
			outputExp.add(interventionCode10);
			outputExp.add(interventionCode11);
			outputExp.add(interventionCode12);
			outputExp.add(interventionCode13);
			outputExp.add(interventionCode14);
			outputExp.add(interventionCode15);
			outputExp.add(interventionCode16);
			outputExp.add(interventionCode17);
			outputExp.add(interventionCode18);
			outputExp.add(interventionCode19);
			outputExp.add(interventionCode20);
			outputExp.add(statusAttributeCode1);
			outputExp.add(statusAttributeCode2);
			outputExp.add(statusAttributeCode3);
			outputExp.add(statusAttributeCode4);
			outputExp.add(statusAttributeCode5);
			outputExp.add(statusAttributeCode6);
			outputExp.add(statusAttributeCode7);
			outputExp.add(statusAttributeCode8);
			outputExp.add(statusAttributeCode9);
			outputExp.add(statusAttributeCode10);
			outputExp.add(statusAttributeCode11);
			outputExp.add(statusAttributeCode12);
			outputExp.add(statusAttributeCode13);
			outputExp.add(statusAttributeCode14);
			outputExp.add(statusAttributeCode15);
			outputExp.add(statusAttributeCode16);
			outputExp.add(statusAttributeCode17);
			outputExp.add(statusAttributeCode18);
			outputExp.add(statusAttributeCode19);
			outputExp.add(statusAttributeCode20);
			outputExp.add(locationAttributeCode1);
			outputExp.add(locationAttributeCode2);
			outputExp.add(locationAttributeCode3);
			outputExp.add(locationAttributeCode4);
			outputExp.add(locationAttributeCode5);
			outputExp.add(locationAttributeCode6);
			outputExp.add(locationAttributeCode7);
			outputExp.add(locationAttributeCode8);
			outputExp.add(locationAttributeCode9);
			outputExp.add(locationAttributeCode10);
			outputExp.add(locationAttributeCode11);
			outputExp.add(locationAttributeCode12);
			outputExp.add(locationAttributeCode13);
			outputExp.add(locationAttributeCode14);
			outputExp.add(locationAttributeCode15);
			outputExp.add(locationAttributeCode16);
			outputExp.add(locationAttributeCode17);
			outputExp.add(locationAttributeCode18);
			outputExp.add(locationAttributeCode19);
			outputExp.add(locationAttributeCode20);
			outputExp.add(extentAttribute1);
			outputExp.add(extentAttribute2);
			outputExp.add(extentAttribute3);
			outputExp.add(extentAttribute4);
			outputExp.add(extentAttribute5);
			outputExp.add(extentAttribute6);
			outputExp.add(extentAttribute7);
			outputExp.add(extentAttribute8);
			outputExp.add(extentAttribute9);
			outputExp.add(extentAttribute10);
			outputExp.add(extentAttribute11);
			outputExp.add(extentAttribute12);
			outputExp.add(extentAttribute13);
			outputExp.add(extentAttribute14);
			outputExp.add(extentAttribute15);
			outputExp.add(extentAttribute16);
			outputExp.add(extentAttribute17);
			outputExp.add(extentAttribute18);
			outputExp.add(extentAttribute19);
			outputExp.add(extentAttribute20);
			outputExp.add(anaestheticTechnique1);
			outputExp.add(anaestheticTechnique2);
			outputExp.add(anaestheticTechnique3);
			outputExp.add(anaestheticTechnique4);
			outputExp.add(anaestheticTechnique5);
			outputExp.add(anaestheticTechnique6);
			outputExp.add(anaestheticTechnique7);
			outputExp.add(anaestheticTechnique8);
			outputExp.add(anaestheticTechnique9);
			outputExp.add(anaestheticTechnique10);
			outputExp.add(anaestheticTechnique11);
			outputExp.add(anaestheticTechnique12);
			outputExp.add(anaestheticTechnique13);
			outputExp.add(anaestheticTechnique14);
			outputExp.add(anaestheticTechnique15);
			outputExp.add(anaestheticTechnique16);
			outputExp.add(anaestheticTechnique17);
			outputExp.add(anaestheticTechnique18);
			outputExp.add(anaestheticTechnique19);
			outputExp.add(anaestheticTechnique20);
			outputExp.add(oohIndicator1);
			outputExp.add(oohIndicator2);
			outputExp.add(oohIndicator3);
			outputExp.add(oohIndicator4);
			outputExp.add(oohIndicator5);
			outputExp.add(oohIndicator6);
			outputExp.add(oohIndicator7);
			outputExp.add(oohIndicator8);
			outputExp.add(oohIndicator9);
			outputExp.add(oohIndicator10);
			outputExp.add(oohIndicator11);
			outputExp.add(oohIndicator12);
			outputExp.add(oohIndicator13);
			outputExp.add(oohIndicator14);
			outputExp.add(oohIndicator15);
			outputExp.add(oohIndicator16);
			outputExp.add(oohIndicator17);
			outputExp.add(oohIndicator18);
			outputExp.add(oohIndicator19);
			outputExp.add(oohIndicator20);
			outputExp.add(mcc);
			outputExp.add(mccPartition);
			outputExp.add(mccSubPartition);
			outputExp.add(cmg);
			outputExp.add(coMorbidityLevel);
			outputExp.add(flaggedInterventionStatusCode);
			outputExp.add(interventionEventCountCode);
			outputExp.add(interventionOOHCountCode);
			//update below for exp.. actually contains output fields//
			//outputExp.add(everythingElse);
			outputExp.add(grouperVersion);
			outputExp.add(trimDays);
			outputExp.add(oohPTCAFlag);
			outputExp.add(oohPaceMakerImplantFlag);
			outputExp.add(interventionOOHReturnCode);
			outputExp.add(interventionOOHCountCode);
			outputExp.add(oohProcedureCategory);
			outputExp.add(oohCardiacCathFlag);
			outputExp.add(firstInterventionUsedForCMGSplit);
			outputExp.add(statusAttributeUsedForCMGSplit);
			outputExp.add(statusAttributeUsedForCMGAssignment);
			outputExp.add(locationAttributeUsedForCMGSplit);
			outputExp.add(locationAttributeUsedForCMGAssignment);
			outputExp.add(extentAttributeUsedForCMGSplit);
			outputExp.add(extentAttributeUsedForCMGAssignment);
			outputExp.add(interventionEventReturnCode);
			outputExp.add(interventionEventCountCode);
			outputExp.add(interventionEpisodeUsedForCMGAssignment);
			outputExp.add(interventionUsedForCMGAssignment);
			outputExp.add(inpatientRIWValue);
			outputExp.add(inpatientRItotalfactor);
			outputExp.add(inpatientRIperdiem);
			outputExp.add(inpatientRIlevel);
			outputExp.add(inpatientRIWAtypicalCode);
			outputExp.add(flaggedInterventionReturnCode);
			outputExp.add(flaggedInterventionStatusCode);
			outputExp.add(eLOSDays);
			outputExp.add(elosReturnCode);
			outputExp.add(firstdxCodeUsedInCMGSplit);
			outputExp.add(dxTypeUsedForCMGAssignment);
			outputExp.add(dxCodeUsedForCMGAssignment);
			outputExp.add(coMorbidityTotalFactor);
			outputExp.add(coMorbidityReturnCode);
			outputExp.add(coMorbidityLevel);
			outputExp.add(coMorbidityCountCode);
			outputExp.add(coMorbidityTotalCount);
			outputExp.add(cmgWeightCategoryCode);
			outputExp.add(cmgReturnCode);
			outputExp.add(cmg);
			outputExp.add(medicalCMG);
			outputExp.add(inpatientTypicalRIWValue);
			outputExp.add(branchCode);
			outputExp.add(cmgAgeCategoryReturnCode);
			outputExp.add(cmgAgeCategory);
		}
}
